module.exports = {
  // AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

    // AUTH ACTIONS
  ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT: "LOGOUT",
}
